[package]
name = "lsass-dumper"
version = "0.2.0"
edition = "2021"
description = "BYOVD LSASS dumper - Bypass PPL via kernel R/W + hand-crafted minidump"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Services",
    "Win32_System_IO",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_SystemInformation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_ProcessStatus",
    "Win32_System_WindowsProgramming",
    "Win32_System_Registry",
    "Wdk_System_SystemServices",
]}
clap = { version = "4", features = ["derive"] }
obfstr = "0.4"

[features]
default = []
driver-loader = []    # Include SCM driver load/unload logic

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
